

export const COLORS = [
    "Açafrão",
    "Amarelo",
    "Animal Print",
    "Azul",
    "Azul Marinho",
    "Bege",
    "Branco",
    "Camelo",
    "Caramelo",
    "Cinza",
    "Colorida",
    "Coral",
    "Coral Fluor",
    "Creme",
    "Dourado",
    "Ferrugem",
    "Jeans",
    "Laranja",
    "lavanda",
    "Lilás",
    "Marrom",
    "Mescla",
    "Metálico",
    "Metalizado",
    "Monograma",
    "Neutro",
    "Nude",
    "Off White",
    "Onçinha",
    "Orquidea",
    "Palha",
    "Pink Berry",
    "Poa",
    "Prata",
    "Prateado",
    "Preto",
    "Preto e Branco",
    "Python",
    "Rosa",
    "Roxo",
    "Tie Dye",
    "Turquesa",
    "Verde",
    "Vermelho",
    "Vermelho e Rosa",
    "Vinho",
    "Xadrez",
]
