export const FLAVORS = [
    'Abacaxi',
    'Açaí',
    'Amêndoas',
    'Avelã',
    'Banana',
    'Baunilha',
    'Blueberry',
    'Café',
    'Cacau',
    'Canela',
    'Castanha',
    'Chá Verde',
    'Chocolate',
    'Coco',
    'Cookies',
    'Framboesa',
    'Frutas Vermelhas',
    'Goiaba',
    'Laranja',
    'Lichia',
    'Limão',
    'Maçã',
    'Mamão',
    'Maracujá',
    'Matcha',
    'Melancia',
    'Morango',
    'Uva',
    'Outros'
]